version: "3.8"
services:
  parkfind-redis:
    container_name: parkfind-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: seeeeeeong/parkfind-redis
    ports:
      - "6379:6379"

  parkfind-database:
    container_name: parkfind-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: seeeeeeong/parkfind-database
    environment:
      - MARIADB_DATABASE=parkfind
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  blue:
    container_name: parkfind-blue
    build: .
    depends_on:
      - parkfind-database
      - parkfind-redis
    image: seeeeeeong/parkfind-blue
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "8080:8080"
    restart: always

  green:
    container_name: parkfind-green
    build: .
    depends_on:
      - parkfind-database
      - parkfind-redis
    image: seeeeeeong/parkfind-green
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
    ports:
      - "8082:8080"
    restart: always
