version: "3.8"
services:
  app-project-redis:
    container_name: parkfind-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: seeeeeeong/parkfind-redis
    ports:
      - "6379:6379"

  app-project-database:
    container_name: parkfind-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: seeeeeeong/parkfind-database
    environment:
      - MARIADB_DATABASE=park-find
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"