spring:
  profiles:
    active: prod
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}


---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/parkfind
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    show-sql: true

park:
  recommendation:
    base:
      url: http://localhost:8080/dir/
---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://parkfind-database:3306/parkfind
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: parkfind-redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    show-sql: true

park:
  recommendation:
    base:
      url: http://3.37.167.45/dir/